import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/component/navbar";
import TimerComponent from "./component/timerComponent";
import SessionWrapper from "@/app/component/SessionProvider"
import { getServerSession } from "next-auth"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import ClientSideLayout from "./component/users/ClientSideLayout";
import Footer from "./component/Footer";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)


  return (
    <html lang="he" dir="rtl">
      <body className="flex flex-col min-h-screen bg-write">
        <SessionWrapper session={session}>
          <Navbar />
          <TimerComponent />
          <div className="flex flex-1 pt-[105px] pb-[50px]">
        
            <ClientSideLayout />
        
            <main className="flex-1 overflow-y-auto p-4 mr-64 mb-[50px]">
              {children}
            </main>
          </div>
          <Footer />
        </SessionWrapper>
        <Script
          src="https://cdn.enable.co.il/licenses/enable-L35466r8t1ik9ew4-1224-66980/init.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}

